workflows:
  ios_altintohumlar:
    name: iOS Altintohumlar Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa